### PR TITLE
#156004609 Pass Data From MainActivity to DetailActivity

### PR DESCRIPTION
**Pull request by muthash**
**What does this PR do?**
Pass Github java developer's data from MainActivity to DetailActivity

**How should this be manually tested?**
1. Clone the repo
2. Sync/build the application
3. Lunch app with the device emulator

**What are the relevant pivotal tracker stories?**
156004609

**Screenshots**
ezgif com-video-to-gif 1

### CODE REVIEW

**Comment by Kalela** [comment]
Why do you have the developers username both on the picture and on the profile description?

**Comment by muthash** [comment]
I was trying to see where it will fit best. I noticed on black images the username is not visible so I will stick with latter implementation.

**Comment by Kalela** [comment]
Cool. Please post the images. Or update the PR gif.

**Comment by muthash** [comment]
screen shot 2018-08-17 at 11 21 58

**Comment by Kalela** [comment]
LGTM

**Pull request merged**
